run:
  name: "de-realistic-h2-costs-2035"

solving:
  mem_mb: 60000
  solver:
    name: highs
    options: default
  solver_options:
    default:
      threads: 8  # Increased for better performance
      presolve: 'on'
      parallel: 'on'
      time_limit: 7200  # 2 hour time limit
    
scenario:
  clusters:
  - 1
  opts:
  - 'Co2L0.05'  # This matches the CO2 limit above

enable:
  retrieve_cost_data: true

electricity:
  co2limit_enable: true  # Enable hard constraint for very low emissions
  co2limit: 0.05  # Allow 5% of 1990 CO2 emissions (more feasible)

costs:
  emission_prices:
    enable: true
    co2: 300  # EUR/tCO2 - Higher carbon price for scenario 2
  
sector:
  heating: false
  enable_sector: false
