# Complete full-year Germany-only PyPSA simulation
# High-performance settings: 32 threads, 70GB RAM, HiGHS solver

# Enable transmission projects for complete simulation
transmission_projects:  # Section for configuring transmission network expansion projects
  enable: true          # Master switch to enable/disable transmission project processing
  include:              # Specify which types of transmission projects to include
    tyndp2020: true     # Tyndp2020 is the transmission network expansion plan for 2020
    nep: true           # NEP is the new energy plan for 2035
    manual: true        # Manual is the manual transmission network expansion plan for 2035
  status:               # List of project statuses to include in the simulation
  - under_construction  # Include projects currently being built
  - in_permitting      # Include projects in the permitting phase
  - confirmed          # Include projects that are confirmed but not yet started

# High-performance solver settings using HiGHS
solving:                # Configuration for the optimization solver
  solver:               # Solver selection and configuration
    name: highs         # Use HiGHS solver (high-performance open-source solver)
    options: highs-highperf  # Reference to custom solver options defined below
  
  solver_options:       # Custom solver parameter configurations
    highs-highperf:     # Named configuration set for high-performance settings
      threads: 10       # Increase number of parallel threads for the solver (use all available cores if possible)
      solver: "ipm"     # Use Interior Point Method (IPM) algorithm (fast for large LPs)
      run_crossover: "off"  # Disable crossover for faster solving
      small_matrix_value: 1e-5  # Minimum threshold for matrix values
      large_matrix_value: 1e9   # Maximum threshold for matrix values
      primal_feasibility_tolerance: 1e-4  # Loosen tolerance for primal feasibility (faster, but may reduce accuracy)
      dual_feasibility_tolerance: 1e-4    # Loosen tolerance for dual feasibility
      ipm_optimality_tolerance: 1e-3      # Loosen optimality tolerance for faster convergence
      parallel: "on"    # Enable parallel processing
      random_seed: 123  # this makes sure to use same random numbers every time script is run
      presolve: "on"    # Enable presolve to reduce problem size and speed up solving
      time_limit: 18000  # Set a time limit (in seconds) for the solver (optional, adjust as needed)
  # Set memory limit to
  mem_mb: 16000         # Memory limit in megabytes
  
  # Additional solving options for full simulation
  options:               # General solving behavior options
    clip_p_max_pu: 1.e-2   # Ensures that any per-unit generation capacity values (p_max_pu) smaller than 1×10⁻² are clipped (set to that minimum).
    load_shedding: false    # If true, PyPSA would allow demand to be unmet at a high penalty cost; here, the model must meet all demand.
    curtailment_mode: false # If true, the simulation focuses on curtailment analysis rather than cost-optimal dispatch.
    noisy_costs: true       # Adds small random noise to technology costs to break symmetry. Useful to prevent the solver from splitting capacity equally among identical assets in different buses just because they have exactly equal costs.
    skip_iterations: true   # PyPSA-Eur often solves iteratively (e.g., adjusting transmission expansion, capacity factors, or other variables between runs).
    rolling_horizon: false  # If true, the model would solve smaller time windows sequentially (mimicking operational foresight limits).
    seed: 123               # Random number seed for reproducibility when using stochastic elements (e.g., noisy_costs).
    track_iterations: false # If true, stores intermediate results from iterative solves.
    min_iterations: 2       # Minimum number of iterations to perform
    max_iterations: 6       # Maximum number of iterations to perform
    transmission_losses: 2  # 2 means each transmission line has a 2% loss factor applied to High voltage grid power flow.
    linearized_unit_commitment: true  # Uses a linear approximation to unit commitment (on/off behaviour of generators) instead of full MILP.
    horizon: 365            # Number of days in the optimisation horizon.

# High-performance Atlite settings for 2019 weather data
atlite:                  # Configuration for weather data processing library
  nprocesses: 10         # Number of parallel processes for data processing
  cutout_directory: cutouts  # Directory to store processed weather data
  default_cutout: europe-2019-sarah3-era5  # Default weather dataset to use
  show_progress: true    # Suppresses progress bars when generating cutouts — useful in batch runs or when running in logging environments.
  cutouts:               # Specific weather dataset configurations
    europe-2019-sarah3-era5:  # Named dataset configuration
      module: [sarah, era5]   # Use SARAH3 and ERA5 data sources
      x: [5., 16.]            # Focus on Germany coordinates (longitude range)
      y: [47., 56.]           # Focus on Germany coordinates (latitude range)
      dx: 0.3                 # Grid resolution in longitude (degrees)
      dy: 0.3                 # Grid resolution in latitude (degrees)
      time: ['2019', '2019']  # Time period for weather data

# Complete scenario setup
scenario:                # Configuration for different simulation scenarios
  clusters:              # List of clustering resolutions to test
  # - 10                 # 10 spatial nodes for higher resolution
  - 37
  #- 128
  #- 256
  opts:                  # Power sector options for each scenario
  - ''    # 'Co2L0.00'       # changed to: CO2 limit of 0.0% of 1990 emissions (very restrictive)''
  sector_opts:           # Sector coupling options for each scenario
  - ''                   # Empty means pure electricity-only model with no additional sector coupling.
  planning_horizons:     # Future years to simulate              
  # - 2020
  # - 2030
  # - 2040
  - 2035                #  Target year for the energy transition
  # - 2050

# Germany only
countries:               # List of countries to include in the simulation
- DE                     # Germany country code

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2023-01-01"
  end: "2024-01-01"
  inclusive: 'left'

# Enable necessary data retrieval for complete simulation
enable:                  # Master switches for different data processing steps
  retrieve: auto         # Automatically determine what data to retrieve
  retrieve_databundle: true    # Download the main data bundle
  retrieve_cost_data: true     # This ensures you have the most recent cost assumptions for generators, storage, and transmission.
  build_cutout: false          # Don't build weather data from scratch
  retrieve_cutout: true        # Download pre-built weather data
  drop_leap_day: true          # Removes February 29 from the time series.

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2020: 0.701
  2025: 0.524
  2030: 0.297
  2035: 0.000 # set to 0 in 2035 for analyzing purposes, original target was: 0.150 
  2040: 0.000 # 0.071
  2045: 0.000 # 0.032
  2050: 0.000


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  voltages: [220., 300., 330., 380., 400., 500., 750.]
  base_network: osm-prebuilt
  osm-prebuilt-version: 0.6
  gaslimit_enable: false
  gaslimit: false
  co2limit_enable: true
  co2limit: 0.0
  co2base: 1.487e+9

  operational_reserve:
    activate: false
    epsilon_load: 0.02
    epsilon_vres: 0.02
    contingency: 4000

  min_hours:
    iron-air battery: [100] # 100 hours is the minimum storage duration for iron-air battery, preferably 100 hours standard product. longer is always possible due to easier power requirements.

  #max_hours:
    #battery: 12
    #H2: 100
    #Vanadium-Redox-Flow: 12
    #Compressed-Air-Adiabatic: 24
    # Iron-Air: 100

  extendable_carriers:    # Technologies that can be expanded in the optimization
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]  # Generators that can be built
    StorageUnit: []  # Storage units disabled to avoid bug
    Store: [H2]        # Energy stores that can be built (hydrogen storage)
    Link: [H2 pipeline, electrolysis, fuel cell]         # Transmission links that can be built

  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
    StorageUnit: [battery, H2, Vanadium-Redox-Flow, Compressed-Air-Adiabatic, Iron-Air]
    Store: []
    Link: [] # H2 pipeline



  storage_units_p_nom:
    battery: 0.0
    H2: 0.0
    Vanadium-Redox-Flow: 0.0
    Compressed-Air-Adiabatic: 0.0
    Iron-Air: 0.0

  storage_units_p_nom_extendable:
    battery: true
    H2: true
    Vanadium-Redox-Flow: true
    Compressed-Air-Adiabatic: true
    Iron-Air: true
 


  powerplants_filter: (DateOut >= 2023 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
  custom_powerplants: false
  everywhere_powerplants: []

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, hydro]


  estimate_renewable_capacities:
    enable: true
    from_opsd: true
    year: 2023
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar


  autarky:
    enable: false
    by_country: false


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#atlite
atlite:
  default_cutout: europe-2023-sarah3-era5
  nprocesses: 10
  show_progress: true
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    europe-2023-sarah3-era5:
      module: [sarah, era5] # in priority order
      x: [-12., 42.]
      y: [33., 72.]
      dx: 0.3
      dy: 0.3
      time: ['2023', '2023']



# Enable all major sectors for complete simulation
sector:                  # Configuration for different energy sectors
  transport: true
  heating: true
  biomass: false
  industry: false
  shipping: false
  aviation: false
  agriculture: false
  fossil_fuels: true
  
  # District heating settings
  district_heating:      # Configuration for district heating systems
    potential: 0.6       # Maximum potential share of district heating
    progress:             # Yearly progress targets for district heating deployment
      2020: 0.0          # Starting point in 2020
      2025: 0.1          # 10% target by 2025
      2030: 0.25         # 25% target by 2030
      2035: 0.4          # 40% target by 2035
      2040: 0.55         # 55% target by 2040
      2045: 0.75         # 75% target by 2045
      2050: 1.0          # Full potential by 2050
    district_heating_loss: 0.15  # 15% loss in district heating networks
  
  # Enable key technologies
  hydrogen_fuel_cell: true   # Enable hydrogen fuel cell technology
  hydrogen_turbine: true     # Enable hydrogen turbine technology
  SMR: true                  # Enable Steam Methane Reforming
  SMR_cc: true              # Enable Steam Methane Reforming with Carbon Capture
  dac: true                  # Enable Direct Air Capture of CO2
  co2_network: true          # Enable CO2 transport network
  H2_network: true           # Enable hydrogen transport network
  gas_network: true          # Enable natural gas transport network

# Complete biomass configuration
biomass:                  # Configuration for biomass resources
  year: 2035              # Target year for biomass availability
  scenario: ENS_Med        # Medium scenario for biomass estimates
  classes:                 # Different categories of biomass resources
    solid biomass:         # Solid biomass resources
    - Agricultural waste   # Waste from agricultural activities
    - Fuelwood residues    # Residues from fuelwood production
    - Secondary Forestry residues - woodchips  # Forestry processing residues
    - Sawdust             # Sawmill waste products
    - Residues from landscape care  # Maintenance residues
    biogas:                # Biogas resources
    - Manure solid, liquid # Animal waste products
    - Sludge               # Wastewater treatment sludge
    municipal solid waste: # Urban waste resources
    - Municipal waste      # General urban waste

# Enable renewable energy sources
renewable:                # Configuration for renewable energy technologies
  onwind:                 # Onshore wind power
    capacity_per_sqkm: 3  # Maximum capacity per square kilometer
  offwind-ac:             # Offshore wind power (AC connection)
    capacity_per_sqkm: 2  # Maximum capacity per square kilometer
  offwind-dc:             # Offshore wind power (DC connection)
    capacity_per_sqkm: 2  # Maximum capacity per square kilometer
  solar:                  # Solar photovoltaic power
    capacity_per_sqkm: 5.1  # Maximum capacity per square kilometer
  hydro:                  # Hydropower resources
    carriers: [ror, PHS, hydro]  # Types: run-of-river, pumped hydro storage, conventional hydro




# Use 2019 energy data and consumption profiles
energy:                   # Energy system configuration
  energy_totals_year: 2019  # Base year for energy consumption data
  base_emissions_year: 1990  # Base year for emissions calculations
  emissions: CO2            # Greenhouse gas to track


# Load profiles based on 2019
load:                     # Electricity demand configuration
  fill_gaps:              # How to handle missing data in load profiles
    enable: true          # Enable gap filling
    interpolate_limit: 3  # Maximum gap size to interpolate
    time_shift_for_large_gaps: 1w  # Time shift for large data gaps
  manual_adjustments: true  # Allow manual adjustments to load data
  scaling_factor: 1.0     # Multiplies the entire load time series by this factor.
  fixed_year: 2019        # Use 2019 consumption patterns
  supplement_synthetic: true  # Generate synthetic data when real data is missing
  distribution_key:       # This means richer, more populated regions get proportionally more demand assigned.
    gdp: 0.6              # 60% weight for GDP-based distribution
    population: 0.4       # 40% weight for population-based distribution








# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2035
  version: 67a5830
  social_discountrate: 0.02
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.05
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   onwind: 500
  fuel:
    OCGT: 29 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
    CCGT: 29
    gas: 29
    coal: 24.57 # https://businessanalytiq.com/procurementanalytics/index/subbituminous-coal-price-index/
    lignite: 22.11 # https://businessanalytiq.com/procurementanalytics/index/lignite-coal-price-index/
    nuclear: 1.75 # https://markets.businessinsider.com/commodities/uranium-price
    uranium: 1.75
  efficiency:
    Compressed-Air-Adiabatic-bicharger: 0.71
    Iron-Air charge:    1.00
    Iron-Air discharge: 0.50
  investment:
    battery storage:                136 # in EUR/kWh (2015)
    Lithium-Ion-LFP-store-2030:     134 # energy costs in EUR/kWh DC (2020)
    home battery storage:           200 # in EUR/kWh (2015)
    battery inverter:               169 # in EUR/kW AC (2015)
    Lithium-Ion-LFP-bicharger-2030: 169 # power costs in EUR/kW AC(2020)
    home battery inverter:          180 # in EUR/kW AC (2015)
    Iron-Air battery:                     32000  # in EUR/MWh (2020) which includes EPC,Ground, etc.
    Iron-Air inverter:                      169  # in EUR/kW AC (2020)
    Compressed-Air-Adiabatic-store:       28835  # in EUR/MWh (2020) from 30,000 EUR/MWh (2022)
    Compressed-Air-Adiabatic-bicharger: 1658016  # in EUR/MW (2020) from 1,725,000 EUR/MW (2022)
  lifetime:
    battery storage:                    22  # years
    Lithium-Ion-LFP-bicharger-2030:     22  # years
    Iron-Air battery:                   25  # years
    battery inverter:                   15  # years
    Iron-Air inverter:                  15  # years
    Compressed-Air-Adiabatic-store:     40  # years
    Compressed-Air-Adiabatic-bicharger: 40  # years
    
    
    
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    li-ion battery: 0.
    battery inverter: 0.
  emission_prices:
    enable: false
    co2: 0.
    co2_monthly_prices: false


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#lines
lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"
    500.: "Al/St 240/40 4-bundle 380.0"
    750.: "Al/St 560/50 4-bundle 750.0"
  s_max_pu: 0.7
  s_nom_max: .inf
  max_extension: 20000 #MW
  length_factor: 1.25
  reconnect_crimea: true
  under_construction: 'keep' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity
  dynamic_line_rating:
    activate: true
    cutout: europe-2023-sarah3-era5
    correction_factor: 0.95
    max_voltage_difference: false
    max_line_rating: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#links
links:
  p_max_pu: 1.0
  p_nom_max: .inf
  max_extension: .inf #MW
  include_tyndp: true
  under_construction: 'zero' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transformers
transformers:
  x: 0.1
  s_nom: 2000.
  type: ''
