version: 0.35.1
tutorial: false
logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
private:
  keys:
    entsoe_api: null
remote:
  ssh: ''
  path: ''
run:
  prefix: ''
  name: de-co2-scenario-D-2035
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: false
foresight: overnight
transmission_projects:
  enable: false
  include:
    tyndp2020: false
    nep: false
    manual: false
solving:
  solver:
    name: highs
    options: stable_highs  # Enhanced for maximum stability
  solver_options:
    # Primary configuration: HiGHS optimized for numerical stability
    stable_highs:
      threads: 0  # Use all available cores
      presolve: 'on'
      parallel: 'on' 
      time_limit: 7200  # 2 hours - good balance of thoroughness vs speed
      # Balanced numerical tolerances for stability vs performance
      primal_feasibility_tolerance: 1e-7  # Good balance: stable but not excessive
      dual_feasibility_tolerance: 1e-7    # Good balance: stable but not excessive
      ipm_optimality_tolerance: 1e-8      # Slightly tighter for interior point
      # Improved pivot strategies (Devex method)
      simplex_dual_edge_weight_strategy: 1   # Devex pricing
      simplex_primal_edge_weight_strategy: 1 # Devex pricing
      # Stability and scaling options
      simplex_scale_strategy: 2  # Aggressive scaling for better conditioning
      ipm_iteration_limit: 300   # Sufficient iterations for convergence
      run_crossover: 'off'       # Disable crossover for numerical stability
      # Logging and debugging
      highs_debug_level: 1
      log_to_console: true
      mip_rel_gap: 1e-6
      
    # Alternative configuration: HiGHS with relaxed settings if stable fails
    robust_highs:
      threads: 0
      presolve: 'on'
      parallel: 'on'
      time_limit: 10800  # 3 hours for difficult problems
      # Slightly relaxed tolerances for difficult problems
      primal_feasibility_tolerance: 1e-7
      dual_feasibility_tolerance: 1e-7
      ipm_optimality_tolerance: 1e-7
      # Standard pivot strategies
      simplex_dual_edge_weight_strategy: 0   # Automatic selection
      simplex_primal_edge_weight_strategy: 0 # Automatic selection
      simplex_scale_strategy: 1  # Standard scaling
      run_crossover: 'on'        # Enable crossover
      highs_debug_level: 1
      log_to_console: true
      mip_rel_gap: 1e-5
      
    # CPLEX configuration (if available)
    stable_cplex:
      threads: 0  # Use all cores
      emphasis_numerical: 1      # Numerical emphasis for stability
      preprocessing_presolve: 1  # Enable preprocessing
      barrier_algorithm: 0       # Automatic barrier selection
      barrier_crossover: -1     # No crossover for stability
      feasibility_tolerance: 1e-9
      optimality_tolerance: 1e-9
      barrier_converge_tolerance: 1e-12
      time_limit: 7200  # 2 hours
      mip_gap_tolerance: 1e-6
      numerics_scale: 1          # Enable scaling
      
    # Fallback configuration: Conservative settings
    conservative:
      threads: 8  # Reduced parallelism for stability
      presolve: 'off'  # Disable presolving
      parallel: 'off'
      time_limit: 14400  # 4 hours maximum
      primal_feasibility_tolerance: 1e-6
      dual_feasibility_tolerance: 1e-6
      ipm_optimality_tolerance: 1e-6
      simplex_dual_edge_weight_strategy: -1
      simplex_primal_edge_weight_strategy: -1
      highs_debug_level: 2
      log_to_console: true
      mip_rel_gap: 1e-4
      
  # Memory allocation - increased for large problems
  mem_mb: 120000  # 120GB for large networks
  
  # Constraints configuration
  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false
    
  # Enhanced solving options for numerical stability
  options:
    # Preprocessing for better conditioning
    clip_p_max_pu: 1e-3        # Remove very small renewable values
    load_shedding: 10000        # Enable load shedding (10,000 EUR/MWh)
    curtailment_mode: false     # Keep disabled for accuracy
    noisy_costs: false          # Disable for numerical stability
    skip_iterations: false      # Enable transmission expansion iterations
    rolling_horizon: false      # Full temporal resolution
    seed: 12345                 # Fixed seed for reproducibility
    
    # Iteration control for stability
    track_iterations: true      # Monitor convergence behavior
    min_iterations: 2           # Minimum transmission expansion iterations
    max_iterations: 8           # Reasonable maximum to avoid cycling
    
    # Physical modeling
    transmission_losses: 0      # Start without losses for stability
    linearized_unit_commitment: true
    
    # Solver interface
    io_api: 'direct'           # Use direct solver API when available
    assign_all_duals: false    # Reduce memory usage
    
    # Time horizon
    horizon: 365               # Full year optimization
    
    # Post-processing
    post_discretization:
      enable: false            # Disable for initial solve
      line_unit_size: 100      # MW units
      line_threshold: 0.1      # Threshold for rounding
      link_unit_size:
        DC: 100
        H2: 50
      link_threshold:
        DC: 0.1
        H2: 0.1
      fractional_last_unit_size: true
      
  # Model configuration
  model_kwargs:
    solver_dir: '/tmp'         # Temporary directory for solver files
  keep_files: false            # Clean up temporary files
  
  # Memory logging
  mem_logging_frequency: 30    # Log memory usage every 30 seconds
atlite:
  nprocesses: 10
  cutout_directory: cutouts
  default_cutout: europe-2023-sarah3-era5
  show_progress: true
  cutouts:
    europe-2023-sarah3-era5:
      module:
      - sarah
      - era5
      x:
      - 5.0
      - 16.0
      y:
      - 47.0
      - 56.0
      dx: 0.3
      dy: 0.3
      time:
      - '2023'
      - '2023'
scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 2
  opts:
  - Co2L0.00
  sector_opts:
  - ''
  planning_horizons:
  - 2035
countries:
- DE
snapshots:
  start: '2023-01-01'
  end: '2024-01-01'
  inclusive: left
enable:
  retrieve: false
  prepare_links_p_nom: false
  retrieve_databundle: false
  retrieve_cost_data: false
  build_cutout: false
  retrieve_cutout: false
  custom_busmap: false
  drop_leap_day: true
co2_budget:
  2035: 0.0
electricity:
  voltages:
  - 220.0
  - 300.0
  - 380.0
  - 500.0
  base_network: osm-prebuilt
  osm-prebuilt-version: 0.6
  gaslimit_enable: false
  gaslimit: false
  co2limit_enable: true
  co2limit: 0.0
  co2base: 1487000000.0
  operational_reserve:
    activate: false
  max_hours:
    battery: 8
    vanadium: 12
    CAES: 24
    #IronAir: 100
  extendable_carriers:
    Generator:
    - solar
    - onwind
    - offwind-ac
    - CCGT
    - OCGT
    StorageUnit:
    - battery
    - PHS
    Store:
    - IronAir
    - H2
    Link: []
  powerplants_filter: (DateOut >= 2023 or DateOut != DateOut)
  custom_powerplants: false
  everywhere_powerplants: []
  conventional_carriers:
  - nuclear
  - oil
  - OCGT
  - CCGT
  - coal
  - lignite
  - geothermal
  - biomass
  renewable_carriers:
  - solar
  - onwind
  - offwind-ac
  - offwind-dc
  - hydro
  estimate_renewable_capacities:
    enable: true
    from_opsd: true
    from_gem: false
    year: 2023
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar
  autarky:
    enable: false
    by_country: false
renewable:
  onwind:
    cutout: europe-2023-sarah3-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
  offwind-ac:
    cutout: europe-2023-sarah3-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_5.5MW
    capacity_per_sqkm: 2
    clip_p_max_pu: 0.01
  offwind-dc:
    cutout: europe-2023-sarah3-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_5.5MW
    capacity_per_sqkm: 2
    clip_p_max_pu: 0.01
  solar:
    cutout: europe-2023-sarah3-era5
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 19.0
        azimuth: 180.0
    capacity_per_sqkm: 5.1
    clip_p_max_pu: 0.01
  hydro:
    cutout: europe-2023-sarah3-era5
    carriers:
    - ror
    - PHS
    - hydro
conventional:
  unit_commitment: false
  dynamic_fuel_price: false
lines:
  types:
    220.0: Al/St 240/40 2-bundle 220.0
    300.0: Al/St 240/40 3-bundle 300.0
    380.0: Al/St 240/40 4-bundle 380.0
  s_max_pu: 0.7
  length_factor: 1.25
links:
  p_max_pu: 1.0
  length_factor: 1.25
transformers:
  x: 0.1
  s_nom: 2000
  type: ''
dlr:
  activate: false
  correction_factor: 1.0
  max_voltage_difference: false
  max_line_rating: false
load:
  scaling_factor: 1.0
  fixed_year: false
  supplement_synthetic: true
  fill_gaps:
    enable: true
    interpolate_limit: 3
    time_shift_for_large_gaps: '7D'
  manual_adjustments: false
sector:
  transport: false
  heating: false
  biomass: false
  industry: false
  agriculture: false
  enable_sector: false
  district_heating:
    enable: false
    potential: 0.0
costs:
  year: 2035
  version: v0.13.3
  social_discountrate: 0.02
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    CO2 intensity: 0
    discount rate: 0.05
  overwrites:
    capital_cost: {}
    marginal_cost: {}
    efficiency: {}
  fuel:
    OCGT: 25
    CCGT: 25
    gas: 25
    coal: 24.57
    lignite: 22.11
    nuclear: 1.75
    uranium: 1.75
  investment:
    solar: 380
    onwind: 1200
    offwind-ac: 2500
    offwind-dc: 3000
    nuclear: 10871
    CCGT: 850
    OCGT: 400
    battery: 132000
    H2: 94000
    PHS: 2000
  lifetime:
    solar: 25
    onwind: 25
    offwind-ac: 25
    offwind-dc: 25
    nuclear: 50
    CCGT: 25
    OCGT: 25
    battery: 16
    H2: 30
    PHS: 50
  emission_prices:
    enable: true
    co2: 100
    co2_monthly_prices: false
clustering:
  mode: busmap
  focus_weights: false
  administrative:
    level: 0
    countries: {}
  simplify_network:
    to_substations: false
    algorithm: kmeans
    feature: solar+onwind-time
    exclude_carriers: []
  cluster_network:
    algorithm: kmeans
    feature: solar+onwind-time
    exclude_carriers: []
  temporal:
    resolution_elec: 3
    resolution_sector: false
adjustments:
  electricity: false
  sector: false
  runtime: 5h
plotting:
  map:
    boundaries:
    - -11
    - 30
    - 34
    - 71
  nice_names:
    OCGT: Open-Cycle Gas
    CCGT: Combined-Cycle Gas
    offwind-ac: Offshore Wind (AC)
    onwind: Onshore Wind
    solar: Solar
    battery: Battery Storage
    H2: Hydrogen Storage
    PHS: Pumped Hydro Storage
