# PyPSA-EUR configuration for CO2 scenarios comparison
# 4380 timesteps, LP optimization, simplified settings for convergence

# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
# SPDX-License-Identifier: CC0-1.0

version: 0.35.1
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

private:
  keys:
    entsoe_api:

remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name: "de-co2-scenarios-2035"
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

# Disable transmission projects for simplicity
transmission_projects:
  enable: false
  include:
    tyndp2020: false
    nep: false
    manual: false

# HiGHS solver configuration optimized for convergence
solving:
  solver:
    name: highs
    options: default
  
  solver_options:
    default:
      threads: 16
      presolve: 'on'
      parallel: 'on'
      time_limit: 18000  # 5 hours = 18000 seconds
      primal_feasibility_tolerance: 1e-6
      dual_feasibility_tolerance: 1e-6
      ipm_optimality_tolerance: 1e-6
      simplex_dual_edge_weight_strategy: -1  # Auto selection
      simplex_primal_edge_weight_strategy: -1  # Auto selection
      highs_debug_level: 0
      log_to_console: true
      mip_rel_gap: 1e-6
  
  mem_mb: 60000
  
  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false
  
  # Simplified solving options for convergence
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: false      # Must meet all demand
    curtailment_mode: false   # Cost optimization
    noisy_costs: true         # Break symmetry
    skip_iterations: true     # No iterative solving
    rolling_horizon: false    # Full horizon optimization
    seed: 123                 # Reproducibility
    track_iterations: false
    min_iterations: 1         # Single iteration
    max_iterations: 1         # Single iteration
    transmission_losses: 2    # Simple linear transmission losses (2%)
    linearized_unit_commitment: true  # Keep linear
    horizon: 365              # Full year

# Weather data settings - 4380 timesteps (every 2 hours)
atlite:
  nprocesses: 10
  cutout_directory: cutouts
  default_cutout: europe-2023-sarah3-era5
  show_progress: true
  cutouts:
    europe-2023-sarah3-era5:
      module: [sarah, era5]
      x: [5., 16.]
      y: [47., 56.]
      dx: 0.3
      dy: 0.3
      time: ['2023', '2023']

# Scenario setup - will be overridden for each CO2 target
scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 1
  opts:
  - 'Co2L0.15'  # Default 15% - will be overridden
  sector_opts:
  - ''  # Electricity-only
  planning_horizons:
  - 2035

countries:
- DE

# 4380 timesteps = every 2 hours (8760/2 = 4380)
snapshots:
  start: "2023-01-01"
  end: "2024-01-01"
  inclusive: 'left'

# Minimal data retrieval for speed
enable:
  retrieve: auto
  prepare_links_p_nom: false
  retrieve_databundle: false
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  custom_busmap: false
  drop_leap_day: true

# CO2 budget - will be overridden per scenario
co2_budget:
  2035: 0.15  # Default 15% - will be updated per scenario

# Electricity system configuration - simplified for LP
electricity:
  voltages: [220., 300., 380., 500.]
  base_network: osm-prebuilt
  osm-prebuilt-version: 0.6
  gaslimit_enable: false
  gaslimit: false
  co2limit_enable: true
  co2limit: 0.15  # Default 15% - will be overridden
  co2base: 1.487e+9

  operational_reserve:
    activate: false

  max_hours:
    battery: 8
    vanadium: 12
    CAES: 24
    IronAir: 100
    H2: 100

  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, CCGT, OCGT]
    StorageUnit: [battery, H2, PHS]
    Store: [H2]
    Link: []

  powerplants_filter: "(DateOut >= 2023 or DateOut != DateOut)"
  custom_powerplants: false
  everywhere_powerplants: []

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    enable: true
    from_opsd: true
    from_gem: false
    year: 2023
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar

  autarky:
    enable: false
    by_country: false

# Simplified renewable settings
renewable:
  onwind:
    cutout: europe-2023-sarah3-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    clip_p_max_pu: 1.e-2
  offwind-ac:
    cutout: europe-2023-sarah3-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_5.5MW
    capacity_per_sqkm: 2
    clip_p_max_pu: 1.e-2
  solar:
    cutout: europe-2023-sarah3-era5
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 19.
        azimuth: 180.
    capacity_per_sqkm: 5.1
    clip_p_max_pu: 1.e-2
  hydro:
    cutout: europe-2023-sarah3-era5
    carriers: [ror, PHS, hydro]

# Conventional settings
conventional:
  unit_commitment: false
  dynamic_fuel_price: false

# Lines - simplified
lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"
  s_max_pu: 0.7
  length_factor: 1.25

# Links - simplified
links:
  p_max_pu: 1.0
  length_factor: 1.25

# Load configuration
load:
  scaling_factor: 1.0
  fixed_year: false
  supplement_synthetic: true

# DISABLE ALL HEATING AND SECTOR COUPLING
sector:
  transport: false
  heating: false        # DISABLED
  biomass: false
  industry: false
  agriculture: false
  enable_sector: false  # Master switch OFF
  
  district_heating:
    enable: false       # DISABLED
    potential: 0.0

# Cost configuration - realistic 2035 costs
costs:
  year: 2035
  version: v0.13.3
  social_discountrate: 0.02
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.05
  
  overwrites:
    capital_cost: {}
    marginal_cost: {}
    efficiency: {}
  
  fuel:
    OCGT: 25
    CCGT: 25
    gas: 25
    coal: 24.57
    lignite: 22.11
    nuclear: 1.75
    uranium: 1.75
  
  investment:
    solar: 380
    onwind: 1200
    offwind-ac: 2500
    nuclear: 10871
    CCGT: 850
    OCGT: 400
    battery: 132000
    H2: 94000      # Use default H2 costs for comparison
    PHS: 2000
  
  lifetime:
    solar: 25
    onwind: 25
    offwind-ac: 25
    nuclear: 50
    CCGT: 25
    OCGT: 25
    battery: 16
    H2: 30
    PHS: 50

  emission_prices:
    enable: true
    co2: 100  # €100/tCO2
    co2_monthly_prices: false

# Simplified clustering
clustering:
  mode: busmap
  focus_weights: false
  simplify_network:
    to_substations: false
    algorithm: kmeans
    feature: solar+onwind-time
    exclude_carriers: []
  cluster_network:
    algorithm: kmeans
    feature: solar+onwind-time
    exclude_carriers: []
  temporal:
    resolution_elec: 2  # Every 2 hours = 4380 timesteps
    resolution_sector: false

# Adjustments
adjustments:
  electricity: false
  sector: false
  runtime: 5h

# Plotting
plotting:
  map:
    boundaries: [-11, 30, 34, 71]
  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    PHS: "Pumped Hydro Storage"
