# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# Configuration for plotting and visualization

map:
  boundaries: [-11, 30, 34, 71]
  projection: "PlateCarree"
  features:
    coastline: true
    borders: true
    ocean: false

nice_names:
  OCGT: "Open-Cycle Gas"
  CCGT: "Combined-Cycle Gas"
  offwind-ac: "Offshore Wind (AC)"
  offwind-dc: "Offshore Wind (DC)"
  onwind: "Onshore Wind"
  solar: "Solar PV"
  battery: "Battery Storage"
  H2: "Hydrogen Storage"
  PHS: "Pumped Hydro Storage"
  IronAir: "Iron-Air Battery"
  vanadium: "Vanadium Redox Flow"
  CAES: "Compressed Air Storage"

tech_colors:
  solar: "#FFFF00"
  onwind: "#3B6182"
  offwind-ac: "#74A9CF"
  offwind-dc: "#2E86AB"
  CCGT: "#8B4513"
  OCGT: "#CD853F"
  nuclear: "#FF6B6B"
  hydro: "#4FC3F7"
  battery: "#9C27B0"
  H2: "#E91E63"
  PHS: "#00BCD4"
  IronAir: "#FF9800"

balance_map:
  bus_carriers:
    - "AC"

costs:
  EUR_to_USD: 1.1
  discountrate: 0.05
  lifetime: 25
  
plotting:
  countries: ["DE"]
  map:
    boundaries: [-11, 30, 34, 71]
    projection: "PlateCarree"
  costs:
    max_threshold: 100
  energy:
    max_threshold: 15000
