# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

plotting:
  map:
    boundaries: [-11, 30, 34, 71]
    resolution: 10m
    figsize: [7, 7]
    projection: PlateCarree
  costs_max: 1200
  costs_threshold: 0.0005
  energy_max: 20000
  energy_min: -15000
  energy_threshold: 50
  vre_techs: [onwind, offwind-ac, offwind-dc, solar, solar-hsat, offwind-float, hydro]
  conv_techs: [OCGT, CCGT, Nuclear, coal, oil, lignite, biomass, geothermal, waste]
  storage_techs: [hydro+PHS, battery, H2]
  load_carriers: [AC load]
  AC_carriers: [AC line, AC transformer]
  link_carriers: [DC line, Converter AC-DC]
  tech_colors:
    "onwind": "#235ebc"
    "onshore wind": "#235ebc"
    "offwind": "#6895dd"
    "offwind-ac": "#6895dd"
    "offshore wind": "#6895dd"
    "offshore wind ac": "#6895dd"
    "offwind-dc": "#74c6f2"
    "offshore wind dc": "#74c6f2"
    "offwind-float": "#6895dd"
    "offshore wind float": "#6895dd"
    "hydro": "#08ad97"
    "hydro+PHS": "#08ad97"
    "PHS": "#08ad97"
    "pumped hydro storage": "#08ad97"
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    "solar": "#f9d002"
    "solar PV": "#f9d002"
    "solar thermal": "#ffef60"
    "solar-hsat": "#f9d002"
    "OCGT": "#d35050"
    "gas": "#d35050"
    "Natural Gas": "#d35050"
    "CCGT": "#b20101"
    "nuclear": "#ff9000"
    "coal": "#707070"
    "lignite": "#9e5a01"
    "oil": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#b8ea04"
    "biomass": "#0c6013"
    "solid biomass": "#06540d"
    "biogas": "#23932d"
    "waste": "#68896b"
    "geothermal": "#ba91b1"
    "AC line": "#70af1d"
    "AC transformer": "#70af1d"
    "DC line": "#b8ea04"
    "Converter AC-DC": "#b8ea04"
    "load": "#dd2e23"
    "electricity": "#dd2e23"
    "lines": "#70af1d"
    "transmission lines": "#70af1d"
    "Co2 Limit": "#f07470"
    "IronAir": "#9e5a01"
    "Co2": "#f07470"
    "co2": "#f07470"
    "co2 stored": "#f07470"
    "DAC": "#ff5270"
    "process emissions CC": "#000000"
    "process emissions": "#000000"
    "solid biomass for industry CC": "#06540d"
    "solid biomass for industry": "#06540d"
    "gas for industry CC": "#d35050"
    "gas for industry": "#d35050"
    "Fischer-Tropsch": "#25c49a"
    "kerosene for aviation": "#ba91b1"
    "naphtha for industry": "#333333"
    "land transport oil": "#444444"
    "water tanks": "#e4e7fa"
    "hot water storage": "#e4e7fa"
    "hot water charging": "#e4e7fa"
    "hot water discharging": "#e4e7fa"
    "CHP": "#8A2BE2"
    "CHP CC": "#8A2BE2"
    "PtL": "#007A8C"
    "Sabatier": "#f5c4a5"
    "methanolisation": "#f5c4a5"
    "helmeth": "#e899a7"
    "Haber-Bosch": "#ff1493"
    "ammonia": "#ff1493"
    "SMR": "#870000"
    "SMR CC": "#870000"
    "steam reforming": "#870000"
    "steam reforming CC": "#870000"
    "solid oxide electrolyser": "#ff1493"
    "electricity distribution grid": "#f9d002"
    "power lines": "#70af1d"
    "building retrofitting": "#8A2BE2"
    "retrofitting": "#8A2BE2"
    "BEV charger": "#bdd6d5"
    "V2G": "#e8e2ca"
    "transport fuel cell": "#5c9291"
    "process emissions to stored": "#000000"
    "process emissions to atmosphere": "#aaaaaa"
    "electricity": "#dd2e23"
    "gas": "#d35050"
    "H2 for industry": "#ea048a"
    "H2 for shipping": "#ea048a"
    "H2": "#ea048a"
    "gas for industry": "#d35050"
    "solid biomass for industry": "#06540d"
    "industry electricity": "#dd2e23"
    "industry new electricity": "#dd2e23"
    "agriculture electricity": "#dd2e23"
    "agriculture machinery oil": "#444444"
    "agriculture heat": "#dd2e23"
    "low-temperature heat for industry": "#dd2e23"
    "process heat": "#dd2e23"
    "heat": "#dd2e23"
    "rural heat": "#dd2e23"
    "central heat": "#dd2e23"
    "decentral heat": "#dd2e23"
    "low-temperature heat": "#dd2e23"
    "heat pump": "#40A9A8"
    "air heat pump": "#40A9A8"
    "ground heat pump": "#40A9A8"
    "Ambient": "#262626"
    "Electric load": "#f9d002"
    "Heat load": "#dd2e23"
    "heat": "#dd2e23"
    "rural water tanks": "#e4e7fa"
    "services rural water tanks": "#e4e7fa"
    "services urban decentral water tanks": "#e4e7fa"
    "urban central water tanks": "#e4e7fa"
    "decentral water tanks": "#e4e7fa"
    "residential rural water tanks": "#e4e7fa"
    "services water tanks": "#e4e7fa"
    "residential urban decentral water tanks": "#e4e7fa"
    "residential water tanks": "#e4e7fa"
    "Sabatier": "#f5c4a5"
    "methanolisation": "#e899a7"
    "helmeth": "#e899a7"
    "electricity": "#dd2e23"
    "gas": "#d35050"
    "H2": "#ea048a"
    "process emissions to stored": "#000000"
    "process emissions to atmosphere": "#aaaaaa"
    "CC": "#f07470"
    "co2": "#f07470"
    "co2 stored": "#f07470"
    "DAC": "#ff5270"
    "Sabatier": "#f5c4a5"
    "co2 vent": "#aaaaaa"
    "solid biomass": "#06540d"
    "methanol": "#c9c9c9"
    "shipping methanol": "#c9c9c9"
    "land transport fuel cell": "#5c9291"
    "biogas": "#23932d"
    "methanation": "#c9c9c9"
    "oil": "#262626"
    "transport oil": "#333333"
    "residential oil": "#333333"
    "services oil": "#333333"
    "transport": "#333333"
    "land transport": "#333333"
    "water transport": "#333333"
    "shipping": "#333333"
    "land transport EV": "#bdd6d5"
    "Li ion": "#bdd6d5"
    "BEV": "#bdd6d5"
    "electric": "#bdd6d5"
    "electricity storage": "#bdd6d5"
    "retrofitting": "#8A2BE2"
    "building retrofitting": "#8A2BE2"
    "BEV charger": "#bdd6d5"
    "transport fuel cell": "#5c9291"
    "fuel cell": "#5c9291"
    "H2 Electrolysis": "#ff1493"
    "H2 Fuel Cell": "#ff1493"
    "H2 pipeline": "#f081dc"
    "H2 pipeline retrofitted": "#ba91b1"
    "H2 Store": "#ea048a"
    "allam": "#B98F00"
    "gas pipeline": "#e05b09"
    "gas pipeline new": "#e05b09"
    "central gas boiler": "#d35050"
    "decentral gas boiler": "#d35050"
    "central resistive heater": "#dd2e23"
    "decentral resistive heater": "#dd2e23"
    "central water tanks": "#e4e7fa"
    "decentral water tanks": "#e4e7fa"
    "central thermal storage": "#e4e7fa"
    "decentral thermal storage": "#e4e7fa"
    "decentral air-sourced heat pump": "#40A9A8"
    "central air-sourced heat pump": "#40A9A8"
    "decentral ground-sourced heat pump": "#40A9A8"
    "central ground-sourced heat pump": "#40A9A8"
    "decentral resistive heater": "#dd2e23"
    "central resistive heater": "#dd2e23"
    "micro CHP": "#8A2BE2"
    "decentral solar thermal": "#ffef60"
    "central solar thermal": "#ffef60"
    "decentral biomass boiler": "#0c6013"
    "central biomass boiler": "#0c6013"
    "central gas CHP": "#B98F00"
    "central gas CHP CC": "#B98F00"
    "central biomass CHP": "#0c6013"
    "central biomass CHP CC": "#0c6013"
    "urban central district heating": "#e8e2ca"
    "urban central solid biomass boiler": "#06540d"
    "urban central gas boiler": "#d35050"
    "urban central air-sourced heat pump": "#40A9A8"
    "urban central ground-sourced heat pump": "#40A9A8"
    "urban central resistive heater": "#dd2e23"
    "urban central micro CHP": "#8A2BE2"
    "urban central solar thermal": "#ffef60"
    "urban central biomass boiler": "#0c6013"
    "central": "#e8e2ca"
    "decentral": "#e8e2ca"
    "district heating": "#e8e2ca"

  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro"
    hydro: "Reservoir & Dam"
    battery: "Battery"
    H2: "Hydrogen Storage"
    IronAir: "Iron-Air Battery"
    lines: "Transmission Lines"
    ror: "Run of River"

  balance_map:
    bus_carriers: ["AC"]

  energy_flow:
    bus_carrier: "AC"
    nice_names:
      load: "Electricity demand"
      onwind: "Onshore wind"
      offwind-ac: "Offshore wind (AC)"
      offwind-dc: "Offshore wind (DC)" 
      solar: "Solar PV"
      hydro: "Hydro reservoir"
      ror: "Run of river"
      nuclear: "Nuclear"
      CCGT: "Gas plants"
      OCGT: "Gas peakers"
      coal: "Coal plants"
      oil: "Oil plants"
      biomass: "Biomass plants"
      battery: "Battery storage"
      PHS: "Pumped hydro storage"
      H2: "Hydrogen storage"
      IronAir: "Iron-air storage"
      curtailment: "Renewable curtailment"
