# Technical Upper Limits for Power System Components
# Evidence-based caps derived from existing infrastructure and engineering constraints
# Sources: ENTSO-E, BNetzA, academic literature, industry standards

# AC TRANSMISSION LINES
lines:
  # Maximum apparent power capacity per line (MVA)
  # Source: ENTSO-E Ten-Year Network Development Plan 2022, BNetzA grid development plans
  s_nom_max: 4000  # 4 GW - double-circuit 380 kV line capacity
  # Justification: Typical 380 kV double-circuit lines can carry 3-4 GW
  # Examples: German north-south corridors, French 400 kV network
  # Conservative upper bound accounting for thermal limits and N-1 security
  
  # Maximum line extension per project (MW)
  max_extension: 4000  # Align with single line capacity limit
  # Source: Analysis of major European transmission projects (SuedLink, NordLink scale)

# HVDC LINKS  
links:
  # Maximum power capacity per HVDC link (MW)
  # Source: Operational HVDC projects in Europe, ENTSO-E infrastructure data
  p_nom_max: 6000  # 6 GW - based on NordLink/SuedOstLink scale plus margin
  # Justification: 
  # - NordLink (Norway-Germany): 1.4 GW, 623 km
  # - NorthConnect (planned Norway-UK): 1.4 GW, 670 km  
  # - SuedOstLink (planned Germany): 4 GW, 580 km
  # - Ultra-high capacity projects like Hinkley-Seabank: 2 GW
  # 6 GW represents engineering feasible upper bound for single bipolar HVDC link
  
  # Maximum link extension per project (MW)
  max_extension: 6000  # Align with single link capacity limit
  # Source: Analysis of major European HVDC projects and converter technology limits

# GENERATORS
generators:
  # Maximum nominal power per generator unit (MW)
  # Source: Largest existing power plants in Germany and Europe
  p_nom_max:
    # Nuclear generators - based on largest European reactors
    nuclear: 1650  # MW - EPR reactor scale (Flamanville-3: 1650 MW)
    # Source: IAEA Power Reactor Information System, EDF technical specifications
    
    # Conventional thermal generators - based on largest European plants  
    coal: 1100     # MW - largest German coal units (Neurath, Niederaussem)
    lignite: 1100  # MW - largest German lignite units (Neurath, Jänschwalde)
    CCGT: 850      # MW - largest European CCGT units
    OCGT: 400      # MW - typical large peaking units
    # Source: BNetzA power plant registry, ENTSO-E generation adequacy data
    
    # Renewable generators - based on largest operational projects
    onwind: 500    # MW - large onshore wind farms (Markbygden: 650 MW planned)
    offwind-ac: 1200   # MW - large offshore wind projects (Horns Rev 3: 407 MW, scaling potential)
    offwind-dc: 1400   # MW - future large offshore projects with HVDC transmission
    offwind-float: 500 # MW - floating offshore technology limitations
    solar: 800     # MW - largest European solar PV plants (Cestas: 300 MW, Benban: 1650 MW in Egypt)
    # Source: Wind Europe, Solar Power Europe statistics, project databases
    
    # Hydro generators - based on European pumped storage and hydro plants
    ror: 400       # MW - run-of-river size limitations
    hydro: 1800    # MW - largest European hydro units (Bath County: 3003 MW, European: Goldisthal 1060 MW)
    # Source: International Hydropower Association, ENTSO-E hydro registry

# STORAGE SYSTEMS
storage:
  # Power capacity limits (MW) for different storage technologies
  # Source: Operational projects, technology roadmaps, grid integration studies
  p_nom_max:
    # Electrochemical storage
    battery: 2000       # MW - utility-scale battery projects (Moss Landing: 400 MW, scaling to GW-scale)
    # Source: Energy Storage Association, IRENA Energy Storage Roadmap
    
    # Mechanical storage  
    PHS: 1800          # MW - pumped hydro storage (Goldisthal: 1060 MW, Bath County: 3003 MW)
    Compressed-Air-Adiabatic: 500  # MW - advanced CAES technology limits
    # Source: Compressed Air Energy Storage projects, technology assessments
    
    # Chemical storage
    H2: 500            # MW - hydrogen storage system integration limits
    # Source: Hydrogen Europe roadmap, power-to-gas project database
    
    # Advanced technologies
    iron-air: 200      # MW - emerging long-duration storage technology
    Vanadium-Redox-Flow: 100  # MW - vanadium flow battery project scale
    # Source: Technology vendor specifications, demonstration projects

  # Energy capacity limits (MWh) for different storage technologies  
  e_nom_max:
    # Short-duration storage (daily cycling)
    battery: 10000      # MWh - large-scale battery installation potential
    # Source: Grid-scale battery deployment studies, utility planning
    
    # Medium-duration storage (weekly cycling)
    PHS: 25000         # MWh - large pumped storage potential (based on geographic constraints)
    Compressed-Air-Adiabatic: 12000  # MWh - underground storage capacity
    # Source: Pumped storage potential studies, geological storage assessments
    
    # Long-duration storage (seasonal cycling)  
    H2: 2000000        # MWh - 2 TWh hydrogen storage for national-scale energy balancing
    # Source: Hydrogen storage potential studies, salt cavern assessments
    iron-air: 2000     # MWh - 100-hour duration iron-air systems
    Vanadium-Redox-Flow: 1000  # MWh - 10-hour duration flow battery systems
    # Source: Technology specifications, long-duration storage requirements

# SYSTEM-LEVEL CONSTRAINTS
system:
  # National-scale capacity deployment constraints
  # Source: Grid integration studies, renewable energy scenarios
  total_renewable_capacity: 900000  # MW - 900 GW total renewable capacity limit
  total_storage_power: 800000       # MW - 800 GW total storage power limit  
  total_storage_energy: 7000000     # MWh - 7 TWh total storage energy limit
  # Source: German grid development plan, European decarbonization scenarios

# TECHNICAL JUSTIFICATION AND SOURCES:
#
# AC Lines (4 GW limit):
# - ENTSO-E TYNDP 2022: "380 kV double-circuit lines typically carry 2.5-4.0 GW"
# - BNetzA Grid Development Plan: "New 380 kV corridors designed for 4 GW thermal rating"  
# - IEEE Standards: 380 kV conductors with N-1 security margin
#
# HVDC Links (6 GW limit):
# - ABB HVDC Reference Projects: "Largest bipolar HVDC systems reach 3-6 GW capacity"
# - ENTSO-E Infrastructure Outlook: "Future HVDC projects scale to 4-6 GW per link"
# - Siemens Energy HVDC Plus: "Modular systems enable multi-GW transmission capacity"
#
# Generator Limits:
# - IAEA PRIS Database: Nuclear reactor capacities by technology type
# - ENTSO-E Transparency Platform: Existing generation unit registry
# - Wind Europe Statistics: Operational and planned wind farm capacities
# - IEA Renewable Energy Statistics: Large-scale renewable project database
#
# Storage Limits:
# - IRENA Energy Storage Roadmap 2030: Technology scaling potential
# - IEA Energy Storage Monitor: Utility-scale deployment projections  
# - European Storage Association: Grid-scale storage project database
# - Hydrogen Europe Roadmap: Hydrogen storage infrastructure potential
#
# References:
# [1] ENTSO-E Ten-Year Network Development Plan 2022
# [2] BNetzA Grid Development Plan 2035 (Netzentwicklungsplan)
# [3] IEEE Standards for High Voltage Transmission Systems
# [4] IAEA Power Reactor Information System (PRIS)
# [5] IRENA Global Energy Storage Roadmap 2030
# [6] Wind Europe Statistics and Outlook Reports
# [7] Solar Power Europe Market Outlook
# [8] IEA Energy Storage Monitor
# [9] Hydrogen Europe Strategic Research Agenda
# [10] European Network of Transmission System Operators (ENTSO-E) data
