# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - pip
  - pypsa>=0.35
  - atlite
  - dask
  - geoviews
  - cartopy
  - rasterio
  - rioxarray
  - h5netcdf
  - pytables
  - openpyxl
  - xlrd
  - powerplantmatching
  - country_converter
  - seaborn
  - snakemake-minimal>=8.4
  - memory_profiler
  - yaml
  - click
  - ruamel.yaml
  - pre_commit
  - pip:
    - highspy
    - tsam>=2.3.1
    - chaospy
